NAME := main

SRC_DIR = ./src/
SRC_NAME = fourth.c \
	   main.c

SRC = $(addprefix $(SRC_DIR), $(SRC_NAME))

OBJ_DIR = ./obj/
OBJ_NAME = $(SRC_NAME:.c=.o)
OBJ = $(addprefix $(OBJ_DIR), $(OBJ_NAME))

CC := gcc
CFLAGS := -Wall -Wextra -Werror
INCLUDE := -I./include -I./lib

LIB_DIR = ./lib/
LIB_NAME = ft
LIB = $(LIB_DIR)lib(
